    - name: Install required packages for Grafana
      package:
        name: "{{ ['unzip', 'tar'] }}"
        state: present
      when: ansible_pkg_mgr == 'apt'  # Ubuntu and Debian

    - name: Install required packages for Grafana
      package:
        name: "{{ ['unzip', 'tar'] }}"
        state: present
      when: ansible_pkg_mgr == 'yum'  # CentOS, Amazon, Fedora, RedHat

    - name: Download Grafana binary
      get_url:
        url: "{{ grafana_url }}"
        dest: "/tmp/grafana-{{ grafana_version }}.linux-amd64.tar.gz"

    - name: Extract Grafana binary
      unarchive:
        src: "/tmp/grafana-{{ grafana_version }}.linux-amd64.tar.gz"
        dest: "{{ grafana_install_dir }}"
        remote_src: yes
        creates: "{{ grafana_install_dir }}/grafana-{{ grafana_version }}"

    - name: Remove existing Grafana binary from /usr/local/bin if present
      file:
        path: /usr/local/bin/grafana
        state: absent

    - name: Rename Grafana binary
      file:
        src: /opt/grafana/bin/grafana
        dest: /usr/local/bin/grafana
        state: link
        force: yes

    - name: Create Grafana configuration directory
      file:
        path: "/etc/grafana/"
        state: directory

    - name: Copy Grafana configuration file
      copy:
        src: "{{ grafana_config_src }}"
        dest: "{{ grafana_config_dest }}"

    - name: Create Grafana service file
      copy:
        src: "{{ grafana_service_src }}"
        dest: "{{ grafana_service_dest }}"

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Start Grafana service and enable it on boot
      service:
        name: grafana-server
        state: started
        enabled: yes
