---
# Tasks for installing and configuring Nginx based on OS distribution

- name: Install Nginx on Debian/Ubuntu
  apt:
    name: nginx
    state: present
  when: ansible_distribution in ["Debian", "Ubuntu"]
  tags:
    - nginx
    - install

- name: Install Nginx on Red Hat/CentOS
  yum:
    name: nginx
    state: present
  when: ansible_distribution in ["RedHat", "CentOS"]
  tags:
    - nginx
    - install

- name: Copy Nginx configuration
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_config_path }}"
  notify: Restart nginx
  tags:
    - nginx
    - configure
