- name: Install required packages for Prometheus
  package:
    name: "{{ prometheus_dependencies }}"
    state: present
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Add Prometheus YUM repository
  yum_repository:
    name: prometheus
    description: Prometheus repository
    baseurl: https://packages.prometheus.io/yum
    gpgcheck: yes
    gpgkey: https://prometheus.io/package-gpg-signing-key/signature.asc
    enabled: yes
  when: ansible_pkg_mgr == 'yum' and ansible_os_family == 'RedHat'

- name: Download prometheus package
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.40.0-rc.0/prometheus-2.40.0-rc.0.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz

- name: Extract prometheus package
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /opt/
    remote_src: yes

- name: Remove existing Prometheus directory
  become: yes
  command: rm -rf /opt/prometheus
  ignore_errors: yes

- name: Move Prometheus directory to the final location
  file:
    src: /opt/prometheus-2.40.0-rc.0.linux-amd64
    dest: /opt/prometheus
    state: link
    force: yes


- name: Create a symlink to the prometheus binary
  file:
    src: /opt/prometheus/prometheus
    dest: /usr/local/bin/prometheus
    state: link

- name: Create a symlink to the promtool binary
  file:
    src: /opt/prometheus/promtool
    dest: /usr/local/bin/promtool
    state: link

- name: Create user and group for Prometheus
  user:
    name: prometheus
    state: present
    system: yes
    shell: /bin/false

- name: Set ownership of Prometheus directories
  file:
    path: "{{ item }}"
    owner: prometheus
    group: prometheus
    state: directory
    recurse: yes
  with_items:
    - /opt/prometheus
    - /etc/prometheus
    - /var/lib/prometheus

- name: Copy prometheus configuration file
  copy:
    src: /opt/prometheus/prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus


- name: Reload systemd after adding the service file
  systemd:
    daemon_reload: yes

- name: Start Prometheus service and enable it on boot
  service:
    name: prometheus
    state: started
    enabled: yes

